# Generated by Django 3.1.5 on 2021-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210118_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
